import localFont from "next/font/local";
import "./globals.css";
import Provider from './provider';

import {Nunito} from 'next/font/google'

const MyAppFont=Nunito({subsets:['latin']});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={MyAppFont.className}
      >
        <Provider>
        {children}
        </Provider>
      </body>
    </html>
  );
}